### ISSUE TITLE
Unclear timing results

### ISSUE THREAD

**Issue by h365chen** [TouringPlans/shapeland#2]
Really appreciate for the simulation code. However, I was wondering if you can provide some further explanation on some of the timing results.

I changed to number of agents from 2000 to 8000 and keep all other parameters unchanged. Then I got

| Attraction | Average Wait Time | Queue Type |
|------------|-------------------|------------|
| Eta        | 5.51              | Expedited  |
| Zeta       | 2.50              | Expedited  |
| Epsilon    | 4.51              | Expedited  |
| Delta      | 38.59             | Expedited  |
| Gamma      | 14.15             | Expedited  |
| Beta       | 3.03              | Expedited  |
| Alpha      | 4.51              | Expedited  |
| Eta        | 5.51              | Standby    |
| Zeta       | 2.50              | Standby    |
| Epsilon    | 4.51              | Standby    |
| Delta      | 2.72              | Standby    |
| Gamma      | 7.01              | Standby    |
| Beta       | 2.00              | Standby    |
| Alpha      | 4.51              | Standby    |

I was wondering why `Delta:Expedited` has a longer wait time than `Delta:Standby`? Thanks in advance.

**Comment by TouringPlans** [comment]
Hi h365chen,

Unfortunately, I don't have the time to diagnose problems with the code.
Let me know if you find anything wrong, however.

Thanks!

Len

**Comment by h365chen** [comment]
I didn't examine the implementation closely, but from the YouTube video, it seems `Delta:Expedited` probably means the wait time for standby agents when expedited passes are used for the attraction "Delta", while `Delta:Standby` means when there are not expedited passes, so it is kind of expected that the former has a longer wait time.

Btw, hinted by the line `VERSION = "20K All FP - MIKE"`, I guess the default value for `TOTAL_DAILY_AGENTS` should be 20,000, rather than the current 2,000. Adjusting it to 20000 actually gives much better plots.

Thanks!
